repository:
  name: www_cfgmgmtcamp
  description: The repo for website for cfgmgmtcamp.org
  homepage: https://cfgmgmtcamp.org
  topics: golang, go, configuration-management, config-management, devops, etcd, distributed-systems, graph-theory, choreography
  private: false
  has_issues: true
  has_projects: false
  has_wiki: true
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: schedule
    color: fc2929
  - name: sponsor
    color: d93f0b
  - name: theme
    color: 5319e7
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb

# Collaborators: give specific users access to this repository.
#collaborators:
#  - username: toshywoshy
#    # Note: Only valid on organization-owned repositories.
#    # The permission to grant the collaborator. Can be one of:
#    # * `pull` - can pull, but not push to or administer this repository.
#    # * `push` - can pull and push, but not administer this repository.
#    # * `admin` - can pull, push and administer this repository.
#    permission: push

#  - username: hubot
#    permission: pull
